name: Update README cards
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=Kseen715&hide_border=true&theme=transparent&show=reviews,prs_merged_percentage&show_icons=true&hide_rank=true&include_all_commits=true&disable_animations=true&hide_title=true
          path: metrics/stats.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=Kseen715&card_width=500&&hide_border=true&theme=transparent&langs_count=20&disable_animations=true&layout=compact&hide=Jupyter%20Notebook,Shell,CSS,HTML,Markdown,Powershell,Dockerfile,Jinja,QML,Batchfile,Latte,Blade,Makefile,Ruby,CMake,Objective-C
          path: metrics/top-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics/*.svg
          git commit -m "Update README cards" || exit 0
          for i in 1 2 3; do
            git pull --rebase --autostash origin main && git push && break
            sleep 5
          done
