name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: teuchezh
          template: classic
          base: header, activity, repositories, community
          config_timezone: Europe/Moscow
          # Lines
          plugin_lines: yes
          # Leetcode
          plugin_leetcode: yes
          plugin_leetcode_user: Kseen
          plugin_leetcode_sections: solved
