name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics:v4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          # Base
          base: activity, repositories
          # Core          
          config_timezone: Europe/Moscow
          # Lines
          plugin_lines: yes
          plugin_lines_sections: base
          # Traffic
          plugin_traffic: yes
          # Languages
          plugin_languages: yes
          plugin_languages_other: no
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_analysis_timeout: 60 # 1-60
          plugin_languages_analysis_timeout_repositories: 0 # 0-15
          plugin_languages_limit: 0 # 0-8
          plugin_languages_colors: github
          plugin_languages_threshold: 0.15%
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_ignored: text, csv, svg, xml, json, toml, css, qml, powershell, shell, markdown, md, sh, tex, desktop, latte, html, yaml, yml
          commits_authoring: Denis Korenev, Kseen715, Kseen715@users.noreply.github.com, korenevdn@gmail.com, mrdragonpach@gmail.com, korenev_deni@edu.bstu.ru, Denis Korenev / ディンヤ, kseen
          # Leetcode
          plugin_leetcode: no
          plugin_leetcode_user: Kseen
          plugin_leetcode_sections: solved
          # 16personalities
          plugin_16personalities: no
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits # profile
          plugin_16personalities_scores: yes
